# Sitewide configuration settings. Set `title` to the site title, which
# will be appended to the URL following {{page.title}} |

title: HealthCare.gov
auto: true
server: true
baseurl: 
permalink: /:categories/:title
markdown: rdiscount
exclude:
  - .gitignore
  - README.md
  - privatekey.p12
  - Gemfile
  - Gemfile.lock
languages: &languages
  - name: 'English'
    value: 'en'
  - name: 'Español'
    value: 'es'
audience: &audience
  - name: 'Individuals'
    value: 'individuals'
  - name: 'Businesses'
    value: 'businesses'
status: &status
  - name: 'Insured'
    value: 'insured'
  - name: 'Not Insured'
    value: 'not-insured'
siteurl: 'https://www.healthcare.gov'
searchurl: 'https://search.healthcare.gov'
searchproxy: 'https://www.healthcare.gov'
 
# Custom Collections
# Creates a globally accessible list of posts based on these specified metadata variables
jekyll_collect:
  - topics

# Settings for Google Analytics post sorting
jekyll_ga:
  host: 'insert_host'
  port: 'insert_port'
  service_account_email: insert_email
  key_file: insert_key_file
  key_secret: insert_key_secret
  profileID: insert_profileID
  start: last month         # Beginning of report
  end: now                  # End of report
  metric: ga:pageviews      # Metric code
  segment:                  # optional
  filters:                  # optional
  sort: true                # Sort posts by this metric

# Advanced list sorting
jekyll_sort:
  - src: posts
    by: date
    direction: down
    dest: blogposts
    include_categories:
    - blog
  - src: posts
    by: title
    direction: up
    dest: glossary
    include_categories:
    - glossary

# Prose settings
prose:
  # media: 'assets'
  # rooturl: "_posts"
  # siteurl: "https://www.healthcare.gov/"

states:
  - Alabama
  - Alaska
  - American Samoa
  - Arizona
  - Arkansas
  - California
  - Colorado
  - Connecticut
  - Delaware
  - District of Columbia
  - Florida
  - Georgia
  - Guam
  - Hawaii
  - Idaho
  - Illinois
  - Indiana
  - Iowa
  - Kansas
  - Kentucky
  - Louisiana
  - Maine
  - Maryland
  - Massachusetts
  - Michigan
  - Minnesota
  - Mississippi
  - Missouri
  - Montana
  - Nebraska
  - Nevada
  - New Hampshire
  - New Jersey
  - New Mexico
  - New York
  - North Carolina
  - North Dakota
  - Northern Mariana Islands
  - Ohio
  - Oklahoma
  - Oregon
  - Pennsylvania
  - Puerto Rico
  - Rhode Island
  - South Carolina
  - South Dakota
  - Tennessee
  - Texas
  - Utah
  - Vermont
  - Virginia
  - Virgin Islands
  - Washington
  - West Virginia
  - Wisconsin
  - Wyoming
territories:
  - American Samoa
  - Guam
  - Northern Mariana Islands
  - Puerto Rico
  - Virgin Islands
